year-02/ca298/pizzeria/pizzeria/app1/urls.py
from django.urls import path
from . import views
from .forms import *

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.UserSignupView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(template_name="login.html", authentication_form=UserLoginForm), name='login'),
    path('logout/', views.logout_user, name="logout"),
    path('fill_pizza', views.fill_pizza, name='fill_pizza'),#linked to a Pizza form
    path('my_orders', views.my_orders, name='my_orders'),
    path('fill_detail/<int:pizzaid>', views.fill_detail, name='fill_detail'),#linked to Datail form 
]

year-02/ca298/pizzeria/pizzeria/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app1.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

year-02/ca298/pizzeria/pizzeria/app1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager #creating a user model
    
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

class User(AbstractUser):
    email = models.EmailField('Email', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

class PizzaSize(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    def __str__(self):
        return self.name

class CheeseType(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    def __str__(self):
        return self.name

class SaucesType(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField()
    def __str__(self):
        return self.name

class Pizza(models.Model):
    id = models.AutoField(primary_key=True)

    #foreignkeys
    size = models.ForeignKey(PizzaSize, on_delete=models.CASCADE)
    cheese = models.ForeignKey(CheeseType, null=True, blank=True, on_delete=models.CASCADE)
    sauces = models.ForeignKey(SaucesType, null=True, blank=True, on_delete=models.CASCADE)
    
    #multiple choices
    crust_choices = [
        ('normal', 'normal'),
        ('thin', 'thin'),
        ('gluten-free', 'gluten-free'),
    ]
    crust = models.CharField(max_length=50, choices=crust_choices, default='normal')

    #boolean fields
    pepperoni = models.BooleanField(default=False)
    chicken = models.BooleanField(default=False)
    ham = models.BooleanField(default=False)
    pineapple = models.BooleanField(default=False)
    peppers = models.BooleanField(default=False)
    mushrooms = models.BooleanField(default=False)
    onions = models.BooleanField(default=False)

    def lst_topping(self):
        toppings = [
            ('pepperoni', self.pepperoni),
            ('chicken', self.chicken),
            ('ham', self.ham),
            ('pinapple', self.pineapple),
            ('peppers', self.peppers),
            ('mushrooms', self.mushrooms),
            ('onions', self.onions)]
        result = [t for t, v in toppings if v == True]
        return ", ".join(result)
    
    def __str__(self):
        result = []
        result.append(f"size {self.size}")
        result.append(f"crust {self.crust}")
        if self.cheese:
            result.append(f"cheese {self.cheese}")
        if self.sauces:
            result.append(f"sauces {self.sauces}")
        if self.lst_topping():
            result.append(f"toppings ({self.lst_topping()})")
        return ", ".join(result)

class DeliveryDetail(models.Model):
    id = models.AutoField(primary_key=True)
    fname = models.CharField(max_length=30)
    lname = models.CharField(max_length=30)
    address = models.CharField(max_length=30)
    cardnumber = models.CharField(max_length=16)
    card_expiry_month = models.IntegerField()
    card_expiry_year = models.IntegerField()
    card_cvv = models.CharField(max_length=4)

class PizzaUser(models.Model):
    id = models.AutoField(primary_key=True)
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    detail = models.ForeignKey(DeliveryDetail, on_delete=models.CASCADE, null=True, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)

year-02/ca298/pizzeria/pizzeria/app1/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import ModelForm, ModelChoiceField
from .models import *
from django.db import transaction
from datetime import datetime
from django.contrib.auth.forms import AuthenticationForm

class UserSignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_admin = False
        user.email = self.cleaned_data['username']
        user.save()
        return user

class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = [
            'size',
            'crust',
            'cheese',
            'sauces',
            'pepperoni',
            'chicken',
            'ham',
            'pineapple',
            'peppers',
            'mushrooms',
        ]

class DeliveryDetailForms(forms.ModelForm):
    class Meta:
        model = DeliveryDetail
        fields = [
            'fname',
            'lname',
            'address',
            'cardnumber',
            'card_expiry_month',
            'card_expiry_year',
            'card_cvv',
        ]

    def clean(self): 
        data = self.cleaned_data

        data['fname'] = data['fname'].lower().capitalize()
        data['lname'] = data['lname'].lower().capitalize()
        data['address'] = data['address'].lower()

        cardnumber = data['cardnumber']
        card_expiry_month = data['card_expiry_month']
        card_expiry_year = data['card_expiry_year']
        card_cvv = data['card_cvv']

        if not cardnumber.isdigit():
            raise forms.ValidationError("A card number must be composed only by digts")
        elif len(cardnumber) != 16:
            raise forms.ValidationError("A card number has 16 digits")
            
        if card_expiry_month not in list(range(1,13)):
            raise forms.ValidationError("A month can only be a number between 1-12") 

        curr_year = datetime.now().year
        curr_month = datetime.now().month

        if card_expiry_month + (card_expiry_year * 12) < curr_month + (curr_year * 12):
            raise forms.ValidationError("Expired card error")

        if not card_cvv.isdigit():
            raise forms.ValidationError("A cvv number must be composed only by digts")
        elif len(card_cvv) != 3 and len(card_cvv) != 4:
            raise forms.ValidationError("A cvv number must be 3 or 4 digits long")

        return data

year-02/ca298/pizzeria/pizzeria/app1/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .forms import *

from django.views.generic import CreateView
from django.shortcuts import redirect
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required #you can use @login_required to lock off certain views and require logged in users 

def index(request):
    return render(request, 'index.html')

class UserSignupView(CreateView):
    model = User
    form_class = UserSignupForm
    template_name = 'user_signup.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('my_orders') #when an account is registred redirect to the my_ordecrs page default is #return redirect('/')

class UserLoginView(LoginView):
    template_name='login.html'

def logout_user(request):
    logout(request)
    return redirect("/")

@login_required
def fill_pizza(request):
    if request.method != "POST":
        form = PizzaForm()
        return render(request, 'fill_pizza.html', {'form': form})
    
    form = PizzaForm(request.POST)
    if not form.is_valid():
        return render(request, 'fill_pizza.html', {'form': form})

    pizza_obj = form.save()
    
    return redirect("fill_detail", pizzaid=pizza_obj.id)

@login_required
def fill_detail(request, pizzaid):
    pizza_obj = get_object_or_404(Pizza, id=pizzaid)

    if request.method != "POST":
        form = DeliveryDetailForms()
        return render(request, 'fill_detail.html', {'form': form})

    form = DeliveryDetailForms(request.POST)
    if not form.is_valid():
        return render(request, 'fill_detail.html', {'form': form})
    
    detail_obj = form.save()
    curr_user = request.user
    newPizzaUser = PizzaUser.objects.create(pizza=pizza_obj, detail=detail_obj, user=curr_user)
    newPizzaUser.save()

    return render(request, 'thanks.html', {'order': newPizzaUser})

@login_required
def my_orders(request):
    user = request.user
    orders = PizzaUser.objects.filter(user=user)
    return render(request, 'my_orders.html', {'orders': orders})

year-02/ca298/pizzeria/pizzeria/app1/templates/base.html
{% load static %}
<html>
    <head>
        <title>Pizzeria</title>
        <link rel="icon" type="image/png" href="{% static 'favicon-32x32.png' %}">
        <link rel="shortcut icon" type="image/png" href="{% static 'favicon-32x32.png' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'base.css' %}">
    </head>
    <body>

        <!--Nav bar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-transparent fixed-top">
            <div class="container-fluid">

            <!--Logo-->
            <a class="navbar-brand fs-4" href="#">Fonderia</a>

            <!--T button-->
            <button
                class="navbar-toggler shadow-none border-0"
                type="button"
                data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbar"
                aria-controls="offcanvasNavbar"
                aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>

            <!--SideBar-->
            <div
                class="sidebar offcanvas offcanvas-strat"
                tabindex="-1"
                id="offcanvasNavbar"
                aria-labelledby="offcanvasNavbarLabel"
            >

            <!--sidebar header-->
            <div class="offcanvas-header text-white border-bottom">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Fonderia</h5>
                <button
                    type="button"
                    class="btn-close btn-close-white shadow none"
                    data-bs-dismiss="offcanvas"
                    aria-label="Close"
                    ></button>
            </div>

            <!--sidebar body-->
            <div class="offcanvas-body d-flex flex-colum p-4 p-lg-0">
                <ul class="navbar-nav justify-content-center align-items-center fs-5 flex-grow-1 pe-3">
                <li class="nav-item mx-2">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>


                <li class="nav-item mx-2">
                    <a class="nav-link" href="{% url 'fill_pizza' %}">Create your own pizza</a>
                </li>

                <li class="nav-item mx-2">
                    <a class="nav-link" href="{% url 'my_orders' %}">My Previous orders</a>
                </li>

                </ul>
                <!--Login/register-->
                <div class="d-flex flex-colum justify-contnet-center align-items-center gap-3">

                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}" class="text-decoration-none text-white">Logout</a>
                    {% else %}
                        <a href="{% url 'login' %}" class="text-decoration-none text-white">Login</a>
                        <a
                            href="{% url 'register' %}"
                            class="text-white text-decoration-none px-3 py-1 rounded-4"
                            style="background-color: #a6700d"
                        >Register</a>
                    {% endif %}
                </div>
            </div>
            </div>
        </div>
        </nav>

        <div class="content">
            {% block content %}
            <!-- Content provided by other templates will be filled in here -->
            {% endblock %}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

year-02/ca298/pizzeria/pizzeria/app1/templates/fill_detail.html
{% extends 'base.html' %}

{% block content %}
<!--<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">Buy Now</button>
</form>-->


<style>
    .btn-submit {
        background-color: #a6700d;
        color:white;
        border: none;
    }
    .btn-submit:hover{
        background-color: #a6700d;
        border-color: #a6700d;
    }
</style>

<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="row mb-3">
            <label for="id_fname" class="col-md-4 col-form-label text-md-end">First Name</label>
            <div class="col-md-8">
                {{ form.fname }}
            </div>
        </div>
        <div class="row mb-3">
            <label for="id_lname" class="col-md-4 col-form-label text-md-end">Last Name</label>
            <div class="col-md-8">
                {{ form.lname }}
            </div>
        </div>
        <div class="row mb-3">
            <label for="id_address" class="col-md-4 col-form-label text-md-end">Address</label>
            <div class="col-md-8">
                {{ form.address }}
            </div>
        </div>
        <div class="row mb-3">
            <label for="id_cardnumber" class="col-md-4 col-form-label text-md-end">Card Number</label>
            <div class="col-md-8">
                {{ form.cardnumber }}
            </div>
        </div>
        <div class="row mb-3">
            <label for="id_card_expiry_month" class="col-md-4 col-form-label text-md-end">Card Expiry Month</label>
            <div class="col-md-8">
                {{ form.card_expiry_month }}
            </div>
        </div>
        <div class="row mb-3">
            <label for="id_card_expiry_year" class="col-md-4 col-form-label text-md-end">Card Expiry Year</label>
            <div class="col-md-8">
                {{ form.card_expiry_year }}
            </div>
        </div>
        <div class="row mb-3">
            <label for="id_card_cvv" class="col-md-4 col-form-label text-md-end">CVV</label>
            <div class="col-md-8">
                {{ form.card_cvv }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <button type="submit" class="btn btn-primary btn-submit">Buy Now</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

year-02/ca298/pizzeria/pizzeria/app1/templates/fill_pizza.html
{% extends 'base.html' %}

{% block content %}
<style>
.bottone{
    background-color: #a6700d;
    border:none;
    color: white;
    padding:5px;
    border-radius:5px;
}
</style>
<form action="" method="POST" style="display: flex; flex-direction: column; align-items: flex-start">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="bottone">Order</button>
</form>
{% endblock %}

year-02/ca298/pizzeria/pizzeria/app1/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
  <p>Hi, {{user.email}}</p>
{% else %}
  <p>Log-in or register is required to order a pizza</p>
{% endif%}
<img src="{%static 'pizza-margherita.jpg'%}" alt="pizza">
{% endblock %}

year-02/ca298/pizzeria/pizzeria/app1/templates/login.html
{% extends 'base.html' %}

{% block title %}
    User Login
{% endblock %}

{%  block content %}
<!--   <form action="." method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">SUBMIT</button>
    </form>-->
    <style>
        .form-label {
            font-weight: bold;
        }
        .form-control {
            margin-bottom: 15px;
        }
        .btn-submit {
            background-color: #a6700d;
            border-color: #a6700d;
        }
        .btn-submit:hover {
            background-color: #a6700d;
            border-color: #a6700d;
        }
    </style>
    
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="row mb-3">
                <label for="id_username" class="form-label col-md-4 col-form-label text-md-end">Email</label>
                <div class="col-md-8">
                    {{ form.username }}
                </div>
            </div>
            <div class="row mb-3">
                <label for="id_password" class="form-label col-md-4 col-form-label text-md-end">Password</label>
                <div class="col-md-8">
                    {{ form.password }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4"></div> <!-- Leave the first column empty for spacing -->
                <div class="col-md-8">
                    <button type="submit" class="btn btn-primary btn-submit">login</button>
                </div>
            </div>
        </form>
    </div>
{%  endblock %}

year-02/ca298/pizzeria/pizzeria/app1/templates/my_orders.html
{% extends 'base.html' %}

{% block content %}
    {% if orders %}
        <ul>
            {% for order in orders %}
                <!--<li>Delivery Date: {{ order.date_ordered }} Pizza: {{ order.pizza }}</li>
                <br>-->
                <div class="card" style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                      <li class="list-group-item"><p style="color:#a6700d">Delivery Date:</p> {{ order.date_ordered }}</li>
                      <li class="list-group-item"><p style="color:#a6700d">Pizza:</p> {{ order.pizza }}</li>
                    </ul>
                  </div>
                <br>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You haven't ordered any pizzas</h3>
    {% endif %}
{% endblock %}

year-02/ca298/pizzeria/pizzeria/app1/templates/thanks.html
{% extends 'base.html' %}

{% block content %}   
    <h5> Your order has been completed successfully, enjoy your pizza </h5>

    <p>Address : {{order.detail.address}}</p>
    <p>Date    : {{order.date_ordered}}</p>

    <p>Pizza details:</p>
    <p>size    : {{order.pizza.size}}</p>
    <p>crust   : {{order.pizza.crust}}</p>

    {% if order.pizza.cheese %}
    <p>cheese  : {{order.pizza.cheese}}</p>
    {% endif %}

    {% if order.pizza.sauces %}
    <p>sauces  : {{order.pizza.sauces}}</p>
    {% endif %}
    
    {% if order.pizza.lst_toppings %}    
    <p>toppings: {{order.pizza.lst_topping}}</p>
    {% endif %}

{% endblock %}

year-02/ca298/pizzeria/pizzeria/app1/templates/user_signup.html
{% extends 'base.html' %}

{% block title %}
    User Signup
{% endblock %}

{%  block content %}
<!--    <form action="." method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">SUBMIT</button>
    </form>-->
    <style>
        .form-label {
            font-weight: bold;
        }
        .form-control {
            margin-bottom: 15px;
        }
        .btn-submit {
            background-color: #a6700d;
            border-color: #a6700d;
        }
        .btn-submit:hover {
            background-color: #a6700d;
            border-color: #a6700d;
        }
    </style>
    
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div class="row mb-3">
                <label for="id_username" class="form-label col-md-4 col-form-label text-md-end">Email</label>
                <div class="col-md-8">
                    {{ form.username }}
                </div>
            </div>
            <div class="row mb-3">
                <label for="id_password1" class="form-label col-md-4 col-form-label text-md-end">Password</label>
                <div class="col-md-8">
                    {{ form.password1 }}
                </div>
            </div>
            <div class="row mb-3">
                <label for="id_password2" class="form-label col-md-4 col-form-label text-md-end">Confirm Password</label>
                <div class="col-md-8">
                    {{ form.password2 }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-md-4"></div>
                <div class="col-md-8">
                    <button type="submit" class="btn btn-primary btn-submit">Sign Up</button>
                </div>
            </div>
        </form>
    </div>
{%  endblock %}